//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int News_ID { get; set; }
        public int UserId { get; set; }
        public string News_Name { get; set; }
        public string Image { get; set; }
        public string Contents { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public string CreateIP { get; set; }
        public Nullable<int> Trangthai { get; set; }
        public Nullable<int> STT { get; set; }
        public string IPcapnhat { get; set; }
        public string Nguoicapnhat { get; set; }
        public Nullable<System.DateTime> Ngaycapnhat { get; set; }
        public string Nguoiduyet { get; set; }
        public Nullable<System.DateTime> Ngayduyet { get; set; }
        public string IPduyet { get; set; }
        public Nullable<int> IsType { get; set; }
    }
}
