//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stage
    {
        public int StageId { get; set; }
        public string StageCode { get; set; }
        public string StageTarget { get; set; }
        public Nullable<System.DateTime> StageStart { get; set; }
        public Nullable<System.DateTime> StageEnd { get; set; }
        public Nullable<System.DateTime> StageCompleted { get; set; }
        public Nullable<int> StageStatus { get; set; }
        public string StageDescription { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int ProjectId { get; set; }
    }
}
