//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        public int WorkId { get; set; }
        public int StageId { get; set; }
        public string WorkCode { get; set; }
        public string WorkName { get; set; }
        public Nullable<System.DateTime> WorkStart { get; set; }
        public Nullable<System.DateTime> WorkEnd { get; set; }
        public Nullable<System.DateTime> WorkCompleted { get; set; }
        public Nullable<int> WorkStatus { get; set; }
        public string WorkDescription { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string WorkImage { get; set; }
        public Nullable<int> STT { get; set; }
    }
}
